[package]
name = "advent-of-code"
version = "0.1.0"
authors = ["Paul Emmerich <paul.emmerich@croit.io>"]
edition = "2018"

[dependencies]
permutohedron = "0.2"
itertools = "0.8"
image = "0.22"
modinverse = "0.1"
mod_exp = "1.0"
rayon = "1.2"
