name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Clippy
      run: cargo clippy --all-targets -- -Dwarnings 
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
