name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Clippy
      run: cargo clippy --all-targets -- -Dwarnings 
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
    - name: Execute binaries
      env:
        RUST_BACKTRACE: 1
      run: for file in $(ls -1 src/bin) ; do cargo run --release --bin ${file%.rs} || exit $status ; done

